# verify_gallery_golden.cmake
# 开发者：青蓝
# 开发时间：2026-07-29
# 用途：捕获 Gallery 页面并校验页面集合与 SHA-256 视觉基线。

foreach(variable IN ITEMS GALLERY_EXECUTABLE CAPTURE_DIRECTORY GOLDEN_MANIFEST)
  if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
    message(FATAL_ERROR "${variable} is required")
  endif()
endforeach()

if(NOT EXISTS "${GALLERY_EXECUTABLE}")
  message(FATAL_ERROR "Gallery executable does not exist: ${GALLERY_EXECUTABLE}")
endif()
if(NOT EXISTS "${GOLDEN_MANIFEST}")
  message(FATAL_ERROR "Gallery golden manifest does not exist: ${GOLDEN_MANIFEST}")
endif()

execute_process(
  COMMAND "${GALLERY_EXECUTABLE}" --capture-all "${CAPTURE_DIRECTORY}"
  RESULT_VARIABLE capture_result)
if(NOT capture_result EQUAL 0)
  message(FATAL_ERROR "Gallery capture failed with exit code ${capture_result}")
endif()

file(STRINGS "${GOLDEN_MANIFEST}" expected_lines)
set(expected_count 0)
foreach(line IN LISTS expected_lines)
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  if(NOT line MATCHES "^([^|]+)[|]([0-9a-f]+)$")
    message(FATAL_ERROR "Invalid Gallery golden entry: ${line}")
  endif()
  set(file_name "${CMAKE_MATCH_1}")
  set(expected_hash "${CMAKE_MATCH_2}")
  string(LENGTH "${expected_hash}" expected_hash_length)
  if(NOT expected_hash_length EQUAL 64)
    message(FATAL_ERROR "Invalid Gallery golden hash: ${file_name}")
  endif()
  list(FIND expected_files "${file_name}" expected_index)
  if(NOT expected_index EQUAL -1)
    message(FATAL_ERROR "Duplicate Gallery golden entry: ${file_name}")
  endif()
  list(APPEND expected_files "${file_name}")
  set(capture_file "${CAPTURE_DIRECTORY}/${file_name}")
  if(NOT EXISTS "${capture_file}")
    message(FATAL_ERROR "Missing Gallery capture: ${file_name}")
  endif()
  file(SHA256 "${capture_file}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Gallery golden mismatch: ${file_name}")
  endif()
  math(EXPR expected_count "${expected_count} + 1")
endforeach()

file(GLOB actual_files "${CAPTURE_DIRECTORY}/gallery-*.png")
list(LENGTH actual_files actual_count)
if(NOT actual_count EQUAL expected_count)
  message(FATAL_ERROR "Gallery capture count mismatch: expected ${expected_count}, got ${actual_count}")
endif()
foreach(capture_file IN LISTS actual_files)
  get_filename_component(capture_name "${capture_file}" NAME)
  list(FIND expected_files "${capture_name}" expected_index)
  if(expected_index EQUAL -1)
    message(FATAL_ERROR "Unexpected Gallery capture: ${capture_name}")
  endif()
endforeach()
